name: common
# version should be equal to appVersion
version: 0.0.2
appVersion: 0.0.2
apiVersion: v2
description: A library Helm chart for common logic
type: library
sources:
  - https://github.com/code-tool/helm-charts/tree/main/charts/common
