name: memcached
version: 0.0.1
appVersion: 1.6.39
apiVersion: v2
description: Memcached is an high-performance, distributed memory object caching system,
  generic in nature, but intended for use in speeding up dynamic web applications
type: application
sources:
  - https://github.com/code-tool/helm-charts/tree/main/charts/memcached
dependencies:
  - name: common
    repository: https://code-tool.github.io/helm-charts
    version: 0.x.x
