name: common
version: 0.0.1
-appVersion: 0.18.0
apiVersion: v2
description: ExternalDNS is a Kubernetes addon that configures public DNS servers
  with information about exposed Kubernetes services to make them discoverable.
type: application
sources:
  - https://github.com/code-tool/helm-charts/tree/main/charts/external-dns
dependencies:
- name: common
  repository: https://github.com/code-tool/helm-charts
  version: 0.x.x
