{{- if not .Values.config.existingAdminSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-secret
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if or .Values.secretAnnotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.secretAnnotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  adminUser: {{ required "A valid .Values.config.adminUser entry required!" .Values.config.adminUser | b64enc | quote }}
  adminPassword: {{ required "A valid .Values.config.adminPassword entry required!" .Values.config.adminPassword | b64enc | quote }}
{{- end }}
