{{- if not .Values.config.existingUserlistSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-userlist-secret
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if or .Values.secretAnnotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.secretAnnotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
data:
  userlist.txt: {{ include "pgbouncer.secret.userlist" . | trim | b64enc }}
{{- end -}}
