name: rabbitmq
version: 0.1.1
appVersion: 3.13.7
apiVersion: v2
description: RabbitMQ is an open source general-purpose message broker that is designed
  for consistent, highly-available messaging scenarios (both synchronous and asynchronous).
type: application
sources:
  - https://github.com/code-tool/helm-charts/tree/main/charts/rabbitmq
dependencies:
  - name: common
    repository: https://code-tool.github.io/helm-charts
    version: 0.x.x
