name: rabbitmq
version: 0.0.1
appVersion: 3.13.7
apiVersion: v2
description: RabbitMQ is an open source general-purpose message broker that is designed
  for consistent, highly-available messaging scenarios (both synchronous and asynchronous).
type: application
sources:
  - https://github.com/code-tool/helm-charts/tree/main/charts/pgbouncer
dependencies:
- name: common
  repository: https://github.com/code-tool/helm-charts
  version: 0.x.x
